#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage:"
  echo "  $0 [add/pull]"
  exit 1
fi

operation="$1"

function subtree() {
  local name repo
  name="$1"
  repo="$2"

  git subtree "$operation" --squash --prefix "vim/pack/zenazn/start/$name" "https://github.com/$repo.git" master
}

subtree fugitive    tpope/vim-fugitive
subtree go          fatih/vim-go
subtree javascript  pangloss/vim-javascript
subtree jsx         mxw/vim-jsx
subtree ruby        vim-ruby/vim-ruby
subtree vinegar     tpope/vim-vinegar
subtree fzf.vim     junegunn/fzf.vim
subtree rhubarb     tpope/vim-rhubarb
subtree fzf-tags    zackhsi/fzf-tags
subtree rust        rust-lang/rust.vim
