#!/bin/bash

export PATH

add_to_path() {
  if ! grep -q "\(^\|:\)$1\(:\|$\)" <<< "$PATH"; then
    PATH="$PATH:$1"
  fi
}
prepend_to_path() {
  local path=$(echo "$PATH" | tr : "\n" | grep -v "$1" | tr "\n" :)
  PATH="$1:${path%:}"
}

[ -d "$HOME/bin" ] && add_to_path "$HOME/bin"
