#!/bin/bash

# ssh
alias fingerprint='ssh-keygen -lF'
alias murder="ssh -O exit"
alias avtok='ssh -At avtok.com screen -UxRR'
alias proxy='ssh -ND 8800 avtok.com'

# gpg
alias clearsign='gpg --clearsign -a'
alias encsign='gpg -sea -r'

# git
alias g='git'
alias gs='g s'
alias gg="git grep"
alias HEAD="git rev-parse HEAD"
bash_complete -o default -o nospace -F _git g

# vim
alias v='vim -O'
function vimwhich { vim "$(which "$1")"; }
bash_complete -o default -F _command vimwhich

# Other aliases
alias cpr='rsync -v --progress'
alias ll='ls -alF'
alias utc="date -u"
