#!/bin/bash

# ssh
alias murder="ssh -O exit"
alias dev="mosh dev.avtok.com -- tmux new -AD -s dev"

# git
alias g='git'
alias gs='g s'
alias gg="git grep -I"
alias HEAD="git rev-parse HEAD"
bash_complete -o default -o nospace -F _git g

# vim
alias v='vim -O'
function vimwhich { vim "$(which "$1")"; }
bash_complete -o default -F _command vimwhich

# Other aliases
alias cpr='rsync -v --progress'
alias ll='ls -alF'
alias utc="date -u"
