#!/bin/bash

# Jump tables for ~/git
mkjump t "$HOME/git" <<EOF
EOF

gh() {
  local url

  url=$(git config --get remote.origin.url)
  if [ $? != 0 ]; then
    return $?
  fi
  if [ "${url:0:4}" == "git@" ]; then
    url=$(echo "$url" | sed -E 's|^git@([^:]+):([^.]+)(\.git)?$|https://\1/\2|')
  elif [ "${url:0:8}" == "https://" ]; then
    url="${url%.git}"
  else
    echo "What kind of remote URL is $url anyways?"
    return 1
  fi
  open "$url"
}
